### ISSUE TITLE
Improved udev.rule to avoid uninstalling modemmanger on Linux.

### ISSUE THREAD

**Issue by mrmowgli** [nrobinson2000/po-util#16]
po installs a udev rule, which currently has issues with the Linux ModemManager on Debian and Ubuntu flavors of Linux.  We can change the rule to force ModemManager to ignore our device.

Append the following to the current rules:

`, ENV{ID_MM_DEVICE_IGNORE}="1"`

**Comment by nrobinson2000** [comment]
@mrmowgli I see you made a new issue:
Would something like this work?

```
ACTION=="add", ATTRS{idProduct}=="[cd]00?", ATTRS{idVendor}=="2b04", DRIVERS=="usb", RUN+="chmod a+rw $(ls -1 /dev/* | grep "ttyACM" | tail -1)" , ENV{ID_MM_DEVICE_IGNORE}="1"
```

Seems to work for me 😄 

EDIT: It actually doesn't

**Comment by mrmowgli** [comment]
it should, though I am still testing this.  Make sure when you test you are flushing the original rule:

`udevadm control --reload-rules`

**Comment by mrmowgli** [comment]
This is what ended up working for the photon here.  Still need another for the electron:

```
SUBSYSTEMS=="usb", ACTION=="add", ATTRS{idProduct}=="[cd]00?", ATTRS{idVendor}=="2b04", GROUP="plugdev", RUN+="chmod a+rw $(ls -1 /dev/* | grep "ttyACM" | tail -1)", ENV{ID_MM_DEVICE_IGNORE}="1"
```

**Comment by mrmowgli** [comment]
Ok, the rule is working here.  Closing.
