### ISSUE TITLE
I need users to test if po-util installs on other Linux distributions.

### ISSUE THREAD

**Issue by nrobinson2000** [nrobinson2000/po-util#24]
I have made **po-util** compatible with RHEL and Arch based distros by making **po-util** detect what package manager a system has.  I think it would be better to use one of the methods on this website http://www.cyberciti.biz/faq/find-linux-distribution-name-version-number/, perhaps using `cat /etc/*-release` and `grep` to find the names of distributions to choose the appropriate package manager.

I need to make sure that **po-util** will install properly on fresh RHEL distributions like Fedora and Arch distributions.  There are no CI's that will provide RHEL or Arch, so it would be great if any users of these distributions could test if **po-util** installs correctly on their system.

**Comment by nrobinson2000** [comment]
I am having no luck with Arch and Fedora.  Read more here. https://community.particle.io/t/po-util-a-toolchain-installer-helper-for-linux-and-osx/21015/20?u=nrobinson2000

**Comment by nrobinson2000** [comment]
I was able to get po-util to work on Fedora and Arch.  Basically, `arm-none-eabi-gcc` requires the 32-bit C libraries in order to run.  Read the solution here: https://community.particle.io/t/po-util-a-toolchain-installer-helper-for-linux-and-osx/21015/24?u=nrobinson2000

**Comment by zombielinux** [comment]
At the moment, I am unable to compile after removing and reinstalling all the dependancies of the po-util via the AUR. Specifically, I'm getting the error:

`In file included from ../wiring/inc/spark_wiring_thread.h:31:0,

                 from ../wiring/inc/spark_wiring_watchdog.h:22,

                 from ../wiring/inc/spark_wiring_cloud.h:31,

                 from ../wiring/inc/spark_wiring.h:47,

                 from ./inc/application.h:40,

                 from ./inc/Particle.h:5,
                 from /home/$user/foo/bar/Electron/firmware/main.cpp:1:
/usr/arm-none-eabi/include/c++/6.3.1/mutex: In member function 'bool std::recursive_timed_mutex::_M_timedlock(const __gthread_time_t&)':

/usr/arm-none-eabi/include/c++/6.3.1/mutex:290:69: error: '__gthread_recursive_mutex_timedlock' was not declared in this scope
       { return !__gthread_recursive_mutex_timedlock(&_M_mutex, &__ts); }
                                                                     ^
make[2]: *** [../build/module.mk:267: ../build/target/user/platform-10-m/firmware/main.o] Error 1
make[1]: *** [../../../build/recurse.mk:12: user] Error 2
make: *** [../build/recurse.mk:12: modules/electron/user-part] Error 2
`

Any thoughts?

**Comment by nrobinson2000** [comment]
No idea.  I haven't been testing po-util on Arch recently.
