### ISSUE TITLE
Support extra build flags

### ISSUE THREAD

**Issue by joerocklin** [nrobinson2000/po-util#31]
It would be really awesome to have the ability to pass build flags (such as `-DBUILD_VERSION="nightly-20161121"` or whatever) as part of the `po build` command. Unless I'm missing something, I haven't found where this is an option in the existing system.

**Comment by nrobinson2000** [comment]
Are you suggesting for the flags to added onto the `make` command in the [`build_firmware()` helper function?](https://github.com/nrobinson2000/po-util/blob/master/po-util.sh#L188)

Is this what you mean?
```
build_firmware()
{
  make all -s -C "$BASE_FIRMWARE/"firmware APPDIR="$FIRMWAREDIR" TARGET_DIR="$FIRMWAREDIR/../bin" PLATFORM="$1" "$ADDITIONAL_FLAGS"
}
```

I could make something like:
```
po DEVICE build "ADDITIONAL_FLAGS"
```

**Comment by joerocklin** [comment]
I think so - I'm still getting used to particle's build setup (though have a good bit of background in C/C++). Let me try putting the flags into that function manually and see if it give me the results I'm expecting.

**Comment by joerocklin** [comment]
If I update the `build_firmare` function to the following:
```bash
build_firmware()
{
  make all -s -C "$BASE_FIRMWARE/"firmware APPDIR="$FIRMWAREDIR" TARGET_DIR="$FIRMWAREDIR/../bin" PLATFORM="$1" EXTRA_CFLAGS='-DBUILD_VERSION=\"nightly\"'
}
```
Then the macro gets set, but in order to change it I have to first run `po particle clean` and then rebuild. I hope there's a better way, but this at least let's me take it outside of hardcoded `#define`'s

**Comment by nrobinson2000** [comment]
If you're still in the Particle space I'd recommend upgrading to [neopo](https://nrobinson2000.github.io/neopo/), a replacement for po-util written in Python.

To set `EXTRA_CFLAGS` you can export it before running neopo or prepend it to a neopo call. Examples:

```
$ export EXTRA_CFLAGS="-DBUILD_VERSION=\"nightly\""
$ neopo flash

$ EXTRA_CFLAGS="-DBUILD_VERSION=\"nightly\"" neopo flash
```

Here is the repository:
https://github.com/nrobinson2000/neopo
