### ISSUE TITLE
Missing curl command doesn't fail

### ISSUE THREAD

**Issue by mrmowgli** [nrobinson2000/po-util#35]
When curl isn't detected on the system, ./po-util should error out early and give the reason.

**Comment by nrobinson2000** [comment]
Implementing this, but isn't it very rare that a Linux system would not have curl installed?

**Comment by nrobinson2000** [comment]
Added this in https://github.com/nrobinson2000/po-util/commit/07a93f1f8ff260be8b82b920d400b80db69ca722

**Comment by mrmowgli** [comment]
Super common not to have curl, most Ubuntu systems don't ship with it by
default.
