### ISSUE TITLE
Gcc-arm produces error when space in directory path

### ISSUE THREAD

**Issue by nrobinson2000** [nrobinson2000/po-util#37]
https://community.particle.io/t/po-util-a-toolchain-installer-helper-for-linux-and-osx/21015/38?u=nrobinson2000

**Comment by markuskreitzer** [comment]
Are you working on this or do you have a fix? Anything I can do to help? If you save a project on your iCloud drive, you can't use it because there's a space in the path and there's no way to change that. :-(

**Comment by nrobinson2000** [comment]
I don’t have a solution for using po-util within iCloud drive or a spaced path at the moment, but I’ll do some investigation soon.

**Comment by nrobinson2000** [comment]
What is the exact path of your project by the way? I can make a project in `Documents` that I can build and that will sync with iCloud Drive.

Here's what I did:
```
cd Documents/
po photon init test
cd test
po photon build
```

I can see the `test` project in iCloud Drive just fine.
