### ISSUE TITLE
Out of multiple devices, select the device to flash to?

### ISSUE THREAD

**Issue by aliekens** [nrobinson2000/po-util#39]
We are in a situation where we are developing code for two separate photons, who each need a different firmware (think of a master and slave device). When we want to flash the master firmware to the master device, or the slave firmware to the slave device, we have to disconnect the other device from USB to flash it. 

Ideally, we would like to select the device that needs to be flashed to, as an option for po commands, instead of autodetecting devices. For example, being able to use `po photon flash --device /dev/cu.usbmodem14511` or `po dfu-open -d /dev/cu.usbmodem14511` would be ideal. 

Is this supported? We cannot seem to find something along these lines in the documentation.

Thank you,
Anthony,-

**Comment by nrobinson2000** [comment]
This is currently not supported, but I could gladly implement it as a feature.

**Comment by nrobinson2000** [comment]
I have added this to po-util in both the macOS and Linux versions.

You can now do the following after issuing a `po update` to achieve your desired workflow:

```
po dfu-list # Quickly find any devices in /dev/cu.*
po dfu-open -d /dev/cu.usbmodem1441 # Put a specific device into DFU mode
po photon flash # Flash will not try to put a device into DFU if one is already detected
```

I encourage you to [join the po-util community on gitter](https://gitter.im/po-util/Lobby).

**Comment by aliekens** [comment]
Thanks a lot, Nathan! That was super fast.

**Comment by nrobinson2000** [comment]
I'll close this issue for now, feel free to reopen it if you any more inquiries about this feature.
