### ISSUE TITLE
Create a better logo for po-util

### ISSUE THREAD

**Issue by nrobinson2000** [nrobinson2000/po-util#4]
[![Bountysource](https://api.bountysource.com/badge/issue?issue_id=34230022)](https://www.bountysource.com/issues/34230022-create-a-better-logo-for-po-util?utm_source=34230022&utm_medium=shield&utm_campaign=ISSUE_BADGE)

<img src="https://nrobinson2000.github.io/po-util/logos/po-util.old.png" height="100px" width="100px">
Hi guys,
I created this simple logo in Photoshop today, but I think it is possible to make a better logo for po-util.  If you have any suggestions please post them here.

**Comment by mrmowgli** [comment]
I actually kinda like it all rough like that :)  What aspects are you trying to convey with it?

**Comment by nrobinson2000** [comment]
Thanks.  I want it to convey that po-util makes it easy for users to use dfu-util, particle-cli, and gcc-arm-embedded to locally develop firmware for Particle devices.  I don't know if I should make another logo that is more abstract or have it include `"po-util"` in the design.

**Comment by nrobinson2000** [comment]
@JacobyJunior created these logos for me today.  Should I use the one with the Particle logo or the one without? 
![po-util-particle](https://cloud.githubusercontent.com/assets/9864152/15554136/79ce6a38-22ba-11e6-9e81-2c9efd9dbe1d.png)
![po-util](https://cloud.githubusercontent.com/assets/9864152/15554141/7fed6126-22ba-11e6-975c-d3a7897fcc59.png)

**Comment by nrobinson2000** [comment]
I think I'll try the one without the Particle logo for now.

**Comment by mrmowgli** [comment]
Actually you would need the ok of the particle.io team to use the logo in yours.  So yeah the second one for now. But It does look nice with the logo in there.

**Comment by nrobinson2000** [comment]
Yeah that's what I thought.

**Comment by nrobinson2000** [comment]
I have SVG'd my logo.  It now looks very nice.

![](http://po-util.com/logos/po-util-basic.svg)
