### ISSUE TITLE
po-util colliding with popd alias

### ISSUE THREAD

**Issue by sidwarkd** [nrobinson2000/po-util#42]
Just finished the install of po-util and when I type `po` from a terminal prompt I get a message about popping the last directory. Decided to run `which po` and get the following:
```po: aliased to popd```

I'm running on a Mac and not sure how to get around this. Is there a way to re-alias po-util to something else?

**Comment by nrobinson2000** [comment]
Have you tried unaliasing `po` so it doesn't resolve to `popd`?

You could add `unalias po` in your `.bashrc`, or wherever you prefer.

This would be the best fix IMO.

**Comment by sidwarkd** [comment]
That did the trick, thanks.
