### ISSUE TITLE
Project structure compatibility?

### ISSUE THREAD

**Issue by rei-vilo** [nrobinson2000/po-util#44]
I've created a similar project using po-util and the Particle CLI.

As per the documentation, `po-util` [project structure](https://docs.po-util.com/#project-structure) is 

<img width="303" alt="capture 2018-03-27 a 18 25 35" src="https://user-images.githubusercontent.com/951776/37980887-7eacf7b6-31ec-11e8-8bc9-adf646eec5cf.png">

while Particle's project structure is 

<img width="300" alt="capture 2018-03-27 a 18 25 45" src="https://user-images.githubusercontent.com/951776/37980888-7ecc8220-31ec-11e8-86ee-6b6ff5bcac53.png">

How to make the project created with po-util compatible with Particle CLI?

**Comment by nrobinson2000** [comment]
I just checked, and you should be able to do `particle compile DEVICE firmware`.

**Comment by rei-vilo** [comment]
Thank you, I'll try.

**Comment by nrobinson2000** [comment]
I've released 0.6.8 which adds support for the official Particle project structure and building with the Particle Workbench makefile. https://github.com/nrobinson2000/po/releases/tag/0.6.8

**Comment by nrobinson2000** [comment]
If you're still in the Particle space I'd recommend upgrading to [neopo](https://nrobinson2000.github.io/neopo/), a replacement for po-util written in Python. It integrates natively with Particle Workbench and Particle CLI, using the same project structure and dependencies.

Here is the repository:
https://github.com/nrobinson2000/neopo
