### ISSUE TITLE
 conflicting types for 'STM32_Pin_Info'

### ISSUE THREAD

**Issue by peripitus-iot** [nrobinson2000/po-util#47]
I got the following error when trying to build a simple "hello wold"  project using po-util to build:
I am using Ubuntu 18.04
device: photon

`In file included from /home/ai/Particle/firmware/hal/src/stm32f2xx/dac_hal.c:30:
/home/ai/Particle/firmware/hal/src/stm32f2xx/pinmap_impl.h:47:3: error: conflicting types for 'STM32_Pin_Info'
   47 | } STM32_Pin_Info;
      |   ^~~~~~~~~~~~~~
In file included from ../hal/inc/pinmap_hal.h:64,
                 from ../hal/inc/dac_hal.h:31,
                 from /home/ai/Particle/firmware/hal/src/stm32f2xx/dac_hal.c:27:
../hal/src/stm32f2xx/pinmap_impl.h:40:22: note: previous declaration of 'STM32_Pin_Info' was here
   40 | typedef Hal_Pin_Info STM32_Pin_Info;
      |                      ^~~~~~~~~~~~~~
In file included from /home/ai/Particle/firmware/hal/src/stm32f2xx/dac_hal.c:30:
/home/ai/Particle/firmware/hal/src/stm32f2xx/pinmap_impl.h:50:17: error: conflicting types for 'HAL_Pin_Map'
   50 | STM32_Pin_Info* HAL_Pin_Map(void);
      |                 ^~~~~~~~~~~
In file included from ../hal/inc/pinmap_hal.h:64,
                 from ../hal/inc/dac_hal.h:31,
                 from /home/ai/Particle/firmware/hal/src/stm32f2xx/dac_hal.c:27:
../hal/src/stm32f2xx/pinmap_impl.h:42:15: note: previous declaration of 'HAL_Pin_Map' was here
   42 | Hal_Pin_Info *HAL_Pin_Map(void);
      |               ^~~~~~~~~~~
../build/module.mk:269: recipe for target '../build/target/user/platform-6-m/firmware/hal/src/stm32f2xx/dac_hal.o' failed
make[2]: *** [../build/target/user/platform-6-m/firmware/hal/src/stm32f2xx/dac_hal.o] Error 1
../../../build/recurse.mk:11: recipe for target 'user' failed
make[1]: *** [user] Error 2
../build/recurse.mk:11: recipe for target 'modules/photon/user-part' failed
make: *** [modules/photon/user-part] Error 2
`

Sorry if I put this in a wrong place!

**Comment by nrobinson2000** [comment]
Hey @peripitus-iot,

I've abandoned po-util and moved on to [neopo](https://github.com/nrobinson2000/neopo), my newest Particle development tool. It is far better than po-util and supports the latest deviceOS releases and dependencies.

https://neopo.xyz/

On Ubuntu, you can install neopo with:

```bash
$ bash <(curl -sL neopo.xyz/install)
```

To create, configure, and build a project you can do:

```
$ neopo create myProject
$ cd myProject
$ neopo configure photon 3.0.0
$ neopo build
```

Here is the neopo man page:
https://neopo.xyz/docs/neopo.html

**Comment by peripitus-iot** [comment]
Thank you @nrobinson2000.
