### ISSUE TITLE
Device goes into DFU mode unintentionally when opening serial port on Linux

### ISSUE THREAD

**Issue by nrobinson2000** [nrobinson2000/po-util#7]
I did some testing for po-util on my Linux Mint desktop yesterday.  Everything went smoothly, except for when I tried running `po serial` after using any of my DFU commands that make use of `stty` to change the baud rate to `19200`.
- My DFU commands do `stty -F /dev/ttyACM0 19200` to put my Particle devices into DFU mode.
- `po serial` simply does `screen -S particle /dev/ttyACM0` to open up a serial monitor.

I can do `po dfu-close`, which gets device out of DFU mode by writing null bytes to it, but `po serial` still puts the device into DFU mode.

**The only solution I have found is to unplug and plug in the USB cable several times, and then `po serial` behaves normally.**

@mrmowgli, can you try this on your Linux machine?  Update po-util and then try doing `po dfu-open` and `po serial`, using a device with the `19200` DFU baud rate patch.

**Comment by mrmowgli** [comment]
Will check it out to tonight

**Comment by mrmowgli** [comment]
po dfu-open gets me this: `ls: cannot open directory /dev/vboxusb: Permission denied`

Screen seems to work.  I don't remember setting up any groups or group permissions, and the udev rule I'm not sure is actually working correctly.  I have another udev rule from the install of particle and haven't taken the time to work out which one should be in effect.

**Comment by mrmowgli** [comment]
Ok, looks like there is a minor error message for any unreadable directory. Tried to redirect it but pops up anyway. 
`modem="$(ls -1 /dev/* | grep "ttyACM" | tail -1)" 2> /dev/null` 

Otherwise seems to go through without any fuss.

Where are you getting the DFU baud rate patch from?

**Comment by nrobinson2000** [comment]
The `patch` command recompiles the system firmware and makes it so that `19200` is used as the baud rate for triggering DFU mode.

I have seen an error message too.  It comes from `stty`.

**Comment by nrobinson2000** [comment]
Wouldn't you want to do
```
modem="$(ls -1 /dev/* | grep "ttyACM" | tail -1 2> /dev/null)"
```
?

**Comment by mrmowgli** [comment]
Hrmm the patch command may need to be sudo'd for the df-util part at the end, or told to put it into DFU mode and paused:

```
dfu-suffix -v 2B04 -p D006 -a ../../../build/target/system-part2/platform-6-m/system-part2.dfu
dfu-suffix (dfu-util) 0.9

Copyright 2011-2012 Stefan Schmidt, 2013-2014 Tormod Volden
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Suffix successfully added to file
Serial device PARTICLE_SERIAL_DEV : not available
Flashing using dfu:
dfu-util -d 0x2B04:0xD006 -a 0 -s 0x8060000 -D ../../../build/target/system-part2/platform-6-m/system-part2.dfu
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

dfu-util: Device has DFU interface, but has no DFU functional descriptor
Deducing device DFU version from functional descriptor length
dfu-util: Device has DFU interface, but has no DFU functional descriptor
Deducing device DFU version from functional descriptor length
dfu-util: No DFU capable USB device available
make: *** [program-dfu] Error 74
Saved working directory and index state WIP on latest: 13b470d bump module versions for v0.5.0-rc.2, tinker changed
HEAD is now at 13b470d bump module versions for v0.5.0-rc.2, tinker changed
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

dfu-util: File too short for DFU suffix
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
dfu-util: Device has DFU interface, but has no DFU functional descriptor
Deducing device DFU version from functional descriptor length
dfu-util: Device has DFU interface, but has no DFU functional descriptor
Deducing device DFU version from functional descriptor length
dfu-util: No DFU capable USB device available
```

**Comment by mrmowgli** [comment]
Interesting I get the same message in DFU mode (entering DFU mode via mode buttons).  Perhaps I am missing something here?

**Comment by mrmowgli** [comment]
Or does DFU mode require being logged into the photon from the CLI first?

**Comment by nrobinson2000** [comment]
DFU is not particle-cli dependent

**Comment by nrobinson2000** [comment]
Are you in the `plugdev` group?  Sudo-less dfu requires it

**Comment by mrmowgli** [comment]
Yeah I am, interestingly.  Hang on looking to see which udev.rules I am using.

**Comment by mrmowgli** [comment]
Well there is another issue in here for my photon, you have DFU_Address as:

`DFU_ADDRESS1="2b04:d00a"` but my photon shows up under lsusb as `"2b04:c00a"`

**Comment by nrobinson2000** [comment]
`2b04:d00a` is the electron I think.

Here is the relevant code:

```
if [ "$1" == "photon" ];
then
  git checkout $BRANCH
  DFU_ADDRESS1="2b04:d006"
  DFU_ADDRESS2="0x080A0000"
fi

if [ "$1" == "electron" ];
then
  git checkout $BRANCH
  DFU_ADDRESS1="2b04:d00a"
  DFU_ADDRESS2="0x08080000"
fi
```

**Comment by nrobinson2000** [comment]
Weird.  I just did `lsusb` on my Macbook and my Linux desktop and I got these results:

### Photon

```
Bus 020 Device 001: ID 2b04:c006 2b04 Photon with WiFi  Serial: 00000000050C
```

### Electron

```
Bus 020 Device 002: ID 2b04:c00a 2b04 Electron  Serial: 00000000050C
```

EDIT:
When doing `dfu-util -l`  and `lsusb` with my devices in dfu mode I got: `2b04:d006` for Photon and `2b04:d00a` for Electron. It seems that when the device is in dfu mode the address changes.

EDIT 2:
Here is the udev rules file that po-util uses. https://gist.github.com/monkbroc/b283bb4da8c10228a61e it has the Photon and Electron in it.

**Comment by mrmowgli** [comment]
Hrm that makes sense,  When in DFU mode it changes the addressing and USB ID to allow the firmware to write directly.  Doesn't that mean that we need to manually put the device in DFU mode?  How would the script be able to do it when it can't directly access the right ID?  and then back to the original topic, why is it switching over for you when it's not likely to see the correct ID.

**Comment by nrobinson2000** [comment]
Po-util puts the device into dfu mode usig the `stty` command.  On linux it does `stty -F /dev/ttyACM0 19200`

**Comment by nrobinson2000** [comment]
On Mac I have never had the issue of the device going into dfu mode at unwanted times, so I suspect that this issue is linux-specific.

**Comment by nrobinson2000** [comment]
I just looked, and BINDIR is not saved to the settings file.
```
f [ ! -f $SETTINGS ]
then
  echo BASE_FIRMWARE="$BASE_FIRMWARE" >> $SETTINGS
  echo BRANCH="latest" >> $SETTINGS
  echo PARTICLE_DEVELOP=1 >> $SETTINGS
  echo BINDIR="$BINDIR"
fi
```
I'll try fixing this.

**Comment by mrmowgli** [comment]
Ok.  So I FINALLY think everything is working correctly on my side (Compiling and flashing the firmware with the patch command), however I don't know how you can actually check running firmware version and patch on the device.  Seems to flash it ok and come out of DFU-util on it's own.  Running the `po-util dfu-open` then `po-util  serial` doesn't put it into DFU mode.

**Comment by nrobinson2000** [comment]
I just tested this with a Linux Mint virtual machine on my Macbook Pro, and `po serial` does not put the device into dfu mode. 😄   This probably means that my desktop is just messed up.  _I'm fairly certain that it is, because it is the first PC I have built._

**Comment by mrmowgli** [comment]
Isn't po dfu-open supposed to place the device in DFU mode?

That doesn't happen on my end.  I'm manually putting it in that mode.

I don't think it's just your desktop, it's pretty hard to mess up serial ports in Linux :)

**Comment by mrmowgli** [comment]
Actually, just to check-  what was the idea behind dfu-open and dfu-close?  stty in this case just redirects terminal output to the device.  Were you breaking apart the dfu command so you could run more than one command to the device?  dfu-open only changes our terminal target, and doesn't call dfu-util.

**Comment by nrobinson2000** [comment]
> Isn't po dfu-open supposed to place the device in DFU mode?
> 
> That doesn't happen on my end. I'm manually putting it in that mode.

Have you done `po DEVICE patch` yet?  It makes it so that `19200` is the baud rate to trigger DFU mode.

**Comment by nrobinson2000** [comment]
`po dfu-open` just puts the device into DFU mode.  I made it just because I could.  `po dfu-close` gets the device out of DFU mode by writing null bytes to it.

**Comment by mrmowgli** [comment]
Ah I see.  Apparently it's patch is not actually working, still something to do with udev rules.

dfu-suffix -v 2B04 -p D006 -a ../../../build/target/system-part2/platform-6-m/system-part2.dfu
    dfu-suffix (dfu-util) 0.9

```
Copyright 2011-2012 Stefan Schmidt, 2013-2014 Tormod Volden
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

Suffix successfully added to file
Serial device PARTICLE_SERIAL_DEV : not available
Flashing using dfu:
dfu-util -d 0x2B04:0xD006 -a 0 -s 0x8060000 -D ../../../build/target/system-part2/platform-6-m/system-part2.dfu
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

dfu-util: Device has DFU interface, but has no DFU functional descriptor
Deducing device DFU version from functional descriptor length
dfu-util: Device has DFU interface, but has no DFU functional descriptor
Deducing device DFU version from functional descriptor length
dfu-util: Cannot open DFU device 2b04:d006
dfu-util: No DFU capable USB device available
make: *** [program-dfu] Error 74
Saved working directory and index state WIP on latest: a0791d1 tweak version info for 0.5.1
HEAD is now at a0791d1 tweak version info for 0.5.1
dfu-util 0.9

Copyright 2005-2009 Weston Schmidt, Harald Welte and OpenMoko Inc.
Copyright 2010-2016 Tormod Volden and Stefan Schmidt
This program is Free Software and has ABSOLUTELY NO WARRANTY
Please report bugs to http://sourceforge.net/p/dfu-util/tickets/

dfu-util: File too short for DFU suffix
dfu-util: A valid DFU suffix will be required in a future dfu-util release!!!
dfu-util: Device has DFU interface, but has no DFU functional descriptor
Deducing device DFU version from functional descriptor length
dfu-util: Device has DFU interface, but has no DFU functional descriptor
Deducing device DFU version from functional descriptor length
Opening DFU capable USB device...
ID 2b04:d006
Run-time device DFU version 011a
Claiming USB DFU Interface...
Setting Alternate Setting #0 ...
Determining device status: state = dfuIDLE, status = 0
dfuIDLE, continuing
DFU mode device DFU version 011a
Device returned transfer size 4096
DfuSe interface name: "Internal Flash   "
Downloading to address = 0x080a0000, size = 0
Download  [                         ]   0%            0 bytesFile downloaded successfully
```

**Comment by nrobinson2000** [comment]
Are you 100% sure that you are in the plugdev group?
Check with the `groups` command.

**Comment by mrmowgli** [comment]
Indeed :) Definitely in plugdev, and dialout.  I just checked and the photon is at ttyACM1 not ttyACM0.

**Comment by mrmowgli** [comment]
So looking to see if that is reading correctly

**Comment by nrobinson2000** [comment]
This is weird...

**Comment by nrobinson2000** [comment]
Maybe we should talk to @monkbroc.  He's the one who made the udev file we're using.

**Comment by mrmowgli** [comment]
I have an alternative udev that does essentially the same thing.  Basically you need to change the device to read/writeable for the current user or group.  The udev rule actually looks ok to me, but this could be something else interfering.

`ACTION=="add", ATTRS{idProduct}=="d006", ATTRS{idVendor}=="2b04", DRIVERS=="usb", RUN+="chmod a+rw /dev/ttyACM0"`

**Comment by nrobinson2000** [comment]
What happens if you disable this rule?

**Comment by nrobinson2000** [comment]
We could try to fork @monkbroc's rule file with your improved udev rule in it.

**Comment by monkbroc** [comment]
I get this behavior on Linux as well. The short of it is that Linux remembers the last baud rate and it first opens the port with the old rate, then changes the baud rate in a 2nd operation.

At this point I don't have a good solution other than moving away from the "magic baud rate as a control message" which is what we'll be doing in a future firmware.

**Comment by mrmowgli** [comment]
The rule above doesn't work either.  I realize also we should add the following section to the UDEV rule:  `, ENV{ID_MM_DEVICE_IGNORE}="1"`  so that we don't have to uninstall the modem manager.

Here's what's actually happening (via: udevadm info --export-db) when my device is registered:

P: /devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/tty/ttyACM1
N: ttyACM1
S: serial/by-id/usb-Particle_Photon_with_WiFi_00000000050C-if00
S: serial/by-path/pci-0000:00:14.0-usb-0:1:1.0
E: DEVLINKS=/dev/serial/by-id/usb-Particle_Photon_with_WiFi_00000000050C-if00 /dev/serial/by-path/pci-0000:00:14.0-usb-0:1:1.0
E: DEVNAME=/dev/ttyACM1
E: DEVPATH=/devices/pci0000:00/0000:00:14.0/usb3/3-1/3-1:1.0/tty/ttyACM1
E: ID_BUS=usb
E: ID_MODEL=Photon_with_WiFi
E: ID_MODEL_ENC=Photon\x20with\x20WiFi
E: ID_MODEL_ID=c006
E: ID_PATH=pci-0000:00:14.0-usb-0:1:1.0
E: ID_PATH_TAG=pci-0000_00_14_0-usb-0_1_1_0
E: ID_REVISION=0200
E: ID_SERIAL=Particle_Photon_with_WiFi_00000000050C
E: ID_SERIAL_SHORT=00000000050C
E: ID_TYPE=generic
E: ID_USB_CLASS_FROM_DATABASE=Communications
E: ID_USB_DRIVER=cdc_acm
E: ID_USB_INTERFACES=:020201:0a0000:
E: ID_USB_INTERFACE_NUM=00
E: ID_VENDOR=Particle
E: ID_VENDOR_ENC=Particle
E: ID_VENDOR_ID=2b04
E: MAJOR=166
E: MINOR=1
E: SUBSYSTEM=tty
E: USEC_INITIALIZED=79260394243

**Comment by nrobinson2000** [comment]
> The short of it is that Linux remembers the last baud rate and it first opens the port with the old rate, then changes the baud rate in a 2nd operation.

That's slightly annoying.  Is there a way to just change the baud rate in a single operation?  I think that's why I am not experiencing this on OSX because it does it in one operation

**Comment by nrobinson2000** [comment]
> At this point I don't have a good solution other than moving away from the "magic baud rate as a control message" which is what we'll be doing in a future firmware.

So not using baudrate to trigger DFU mode?

**Comment by nrobinson2000** [comment]
@mrmowgli Why don't you uninstall `modemmanager`?

**Comment by mrmowgli** [comment]
@nrobinson2000 yes I did uninstall it.  We shouldn't actually have to do that part- that line would keep modemmanager from interfering with the port.

**Comment by nrobinson2000** [comment]
I see.  We should try to make an improved udev rules file.  What exactly does `, ENV{ID_MM_DEVICE_IGNORE}="1"` do?

**Comment by nrobinson2000** [comment]
Something like this?

```
ACTION=="add", ATTRS{idProduct}=="[cd]00?", ATTRS{idVendor}=="2b04", DRIVERS=="usb", RUN+="chmod a+rw $(ls -1 /dev/* | grep "ttyACM" | tail -1)"
```

**Comment by mrmowgli** [comment]
splitting the udev.rule to a different issue
